#!/bin/python3
def simpleArraySum(ar_c, ar):
    summ = 0
    for i in range(ar_c):
        summ = ar[i] + summ
    return summ

if __name__ == '__main__':
    ar_count = int(input())
    ar = list(map(int, input().rstrip().split()))
    result = simpleArraySum(ar_count, ar)
    print(result)
